name: reviewdog
on: push

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          reporter: github-check
          fail_on_error: false
          level: warning
          debug: true
          separator: ","
          files: >-
            content/deploy/,content/get-started/,content/how-to/,content/reference/
          vale_flags: '--glob=*.md'
